### ISSUE TITLE
Margin on the body in iframe

### ISSUE THREAD

**Issue by darkeclipz** [fcakyon/streamlit-image-comparison#11]
Is it possible to remove the margin of `8px` that is on the body in the `iframe`?

**Comment by fcakyon** [comment]
If you can open a pr, I would accept after testing :+1:

**Comment by darkeclipz** [comment]
I have created a PR: https://github.com/fcakyon/streamlit-image-comparison/pull/12.

**Comment by fcakyon** [comment]
I have released a new version. Thank you 👍
